services:
  main_front:
    container_name: main_front
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "0.0.0.0:443:443"
      - "0.0.0.0:80:80"
      - "0.0.0.0:8005:8005"
    volumes:
      - pumpkin-user-uploads:/usr/share/nginx/html/uploads
volumes:
  pumpkin-user-uploads:
