services:
  main_front:
    container_name: main_front
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - Pumpkin-network
    volumes:
      - pumpkin-user-uploads:/usr/share/nginx/html/uploads
volumes:
  pumpkin-user-uploads:

networks:
  Pumpkin-network:
    external:
      name: Pumpkin-network
