services:
  main_front:
    container_name: main_front
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode:
      host
    volumes:
      - pumpkin-user-uploads:/usr/share/nginx/html/uploads
volumes:
  pumpkin-user-uploads:
