services:
  main_front:
    container_name: main_front
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - Pumpkin-network

networks:
  Pumpkin-network:
    external: true
